[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[dependencies]
# add crates as you like, e.g. itertools = "0.10"
regex = "1.12.2"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "benchmarks"
harness = false
